namespace Contigu.Core
{
    /// <summary>The enemy roster (see EnemyId's own doc comment) — same All-array-plus-Get-loop convention as ChallengeCatalog.</summary>
    public static class EnemyCatalog
    {
        /// <summary>"Basic" (GDD §07: Baseline, "Low HP. No special effect.") — the round 1 encounter, teaching the damage-by-score mechanic with nothing else going on.</summary>
        public static readonly EnemyDefinition Basic = new EnemyDefinition { Id = EnemyId.Basic, Name = "Basic", Role = EnemyRole.Baseline, MaxHp = 150, Description = "No special effect. A straightforward target to learn the ropes on." };

        /// <summary>"Locker" (GDD §07: Creator, "On each Shuffle, locks 1 grid case. The previous lock is removed at the next Shuffle...") — see RunManager.ResolveLockerShuffleEffect.</summary>
        public static readonly EnemyDefinition Locker = new EnemyDefinition { Id = EnemyId.Locker, Name = "Locker", Role = EnemyRole.Creator, MaxHp = 400, Description = "On each Shuffle, locks 1 grid cell. The previous lock is released first, so only ever one cell is locked at a time." };

        /// <summary>"Poisoner" (GDD §07: Creator, "On each Shuffle, poisons 1 tile. Points generated by poisoned tiles are negative.") — see RunManager.ResolvePoisonerShuffleEffect.</summary>
        public static readonly EnemyDefinition Poisoner = new EnemyDefinition { Id = EnemyId.Poisoner, Name = "Poisoner", Role = EnemyRole.Creator, MaxHp = 700, Description = "On each Shuffle, poisons 1 filled tile. Points scored through a poisoned tile count negative instead of positive." };

        /// <summary>"Heavy Locker" (GDD §07: Creator/Boss, "High HP. Locks one slot/case until the next Shuffle. Killing it removes the current lock and prevents future locks.") — mechanically Locker's own roaming single-cell lock (see RunManager.ResolveLockerShuffleEffect, reused as-is), just at real boss HP.</summary>
        public static readonly EnemyDefinition HeavyLocker = new EnemyDefinition { Id = EnemyId.HeavyLocker, Name = "Heavy Locker", Role = EnemyRole.Boss, MaxHp = 1200, Description = "On each Shuffle, locks 1 grid cell — same roaming lock as Locker, just far tougher. Killing it releases the lock immediately." };

        /// <summary>"Plague" (GDD §07: Creator/Boss, "High HP. Poisons 5 tiles. Points from those tiles are negative. Killing it normalizes its poisoned tiles.") — Poisoner's own roaming-poison mechanic (see RunManager.ResolvePoisonerShuffleEffect), scaled from 1 cell to 5.</summary>
        public static readonly EnemyDefinition Plague = new EnemyDefinition { Id = EnemyId.Plague, Name = "Plague", Role = EnemyRole.Boss, MaxHp = 1800, Description = "On each Shuffle, poisons 5 filled tiles at once (releasing its previous 5 first). Points scored through any of them count negative." };

        /// <summary>"Thief" (GDD §07: Creator/Boss, "High HP. On each Shuffle, steals 1 random tile from the hand.") — see DeckManager.StealRandomHandTile/RunManager.ResolveThiefShuffleEffect.</summary>
        public static readonly EnemyDefinition Thief = new EnemyDefinition { Id = EnemyId.Thief, Name = "Thief", Role = EnemyRole.Boss, MaxHp = 1000, Description = "On each Shuffle, steals 1 random piece from your hand — it's not lost, just unavailable until a later Shuffle draws it again." };

        /// <summary>"Reclaimer" (GDD §07: Reactor/Boss, "On Shuffle, consumes poisoned tiles and heals 1 HP per poisoned tile consumed. Its effectiveness depends on [encounter order]") — see RunManager.ResolveReclaimerShuffleEffect; the order note is GDD §07's own "Order-based interactions" (Poisoner-before-Reclaimer feeds it fresh poison to heal from; the reverse starves it).</summary>
        public static readonly EnemyDefinition Reclaimer = new EnemyDefinition { Id = EnemyId.Reclaimer, Name = "Reclaimer", Role = EnemyRole.Boss, MaxHp = 1100, Description = "On each Shuffle, consumes every currently-poisoned tile on the grid (from any enemy) and heals 1 HP per tile consumed. Goes before a Poisoner in the encounter order to starve it; after, to feed it." };

        /// <summary>"Leech" (GDD §07: Reactor, "High HP. Heals when the player destroys a line. The effect stops when it dies.") — not Boss-tagged, unlike the other 4 new enemies above (per the GDD's own Role column). See RunManager.PlacePiece's own Leech heal hook.</summary>
        public static readonly EnemyDefinition Leech = new EnemyDefinition { Id = EnemyId.Leech, Name = "Leech", Role = EnemyRole.Reactor, MaxHp = 600, Description = "Heals " + ScoringConstants.LeechHealPerLineClear + " HP every time you clear a row or column, for as long as it's alive." };

        private static readonly EnemyDefinition[] All = { Basic, Locker, Poisoner, HeavyLocker, Plague, Thief, Reclaimer, Leech };

        public static EnemyDefinition Get(EnemyId id)
        {
            for (int i = 0; i < All.Length; i++)
            {
                if (All[i].Id == id)
                {
                    return All[i];
                }
            }
            return Basic;
        }
    }
}
