namespace Contigu.Core
{
    /// <summary>The 3 enemies built so far (see EnemyId's own doc comment) — same All-array-plus-Get-loop convention as ChallengeCatalog.</summary>
    public static class EnemyCatalog
    {
        /// <summary>"Basic" (GDD §07: Baseline, "Low HP. No special effect.") — the round 1 encounter, teaching the damage-by-score mechanic with nothing else going on.</summary>
        public static readonly EnemyDefinition Basic = new EnemyDefinition { Id = EnemyId.Basic, Name = "Basic", Role = EnemyRole.Baseline, MaxHp = 150 };

        /// <summary>"Locker" (GDD §07: Creator, "On each Shuffle, locks 1 grid case. The previous lock is removed at the next Shuffle...") — see RunManager.ResolveLockerShuffleEffect.</summary>
        public static readonly EnemyDefinition Locker = new EnemyDefinition { Id = EnemyId.Locker, Name = "Locker", Role = EnemyRole.Creator, MaxHp = 400 };

        /// <summary>"Poisoner" (GDD §07: Creator, "On each Shuffle, poisons 1 tile. Points generated by poisoned tiles are negative.") — see RunManager.ResolvePoisonerShuffleEffect.</summary>
        public static readonly EnemyDefinition Poisoner = new EnemyDefinition { Id = EnemyId.Poisoner, Name = "Poisoner", Role = EnemyRole.Creator, MaxHp = 700 };

        private static readonly EnemyDefinition[] All = { Basic, Locker, Poisoner };

        public static EnemyDefinition Get(EnemyId id)
        {
            for (int i = 0; i < All.Length; i++)
            {
                if (All[i].Id == id)
                {
                    return All[i];
                }
            }
            return Basic;
        }
    }
}
