namespace Contigu.Core
{
    /// <summary>The enemy roster (see EnemyId's own doc comment) — same All-array-plus-Get-loop convention as ChallengeCatalog. Every MaxHp below is +50% over its original value (explicit request: "Augmente de 50% les HP des ennemis (tous)").</summary>
    public static class EnemyCatalog
    {
        /// <summary>"Basic" (GDD §07: Baseline, "Low HP. No special effect.") — the round 1 encounter, teaching the damage-by-score mechanic with nothing else going on.</summary>
        public static readonly EnemyDefinition Basic = new EnemyDefinition { Id = EnemyId.Basic, Name = "Basic", Role = EnemyRole.Baseline, MaxHp = 225, Description = "No special effect. A straightforward target to learn the ropes on." };

        /// <summary>"Locker" (GDD §07: Creator, "On each Shuffle, locks 1 grid case. The previous lock is removed at the next Shuffle...") — see RunManager.ResolveLockerShuffleEffect.</summary>
        public static readonly EnemyDefinition Locker = new EnemyDefinition { Id = EnemyId.Locker, Name = "Locker", Role = EnemyRole.Creator, MaxHp = 600, Description = "On each Shuffle, locks 1 grid cell. The previous lock is released first, so only ever one cell is locked at a time." };

        /// <summary>"Poisoner" (GDD §07: Creator, "On each Shuffle, poisons 1 tile. Points generated by poisoned tiles are negative.") — see RunManager.ResolvePoisonerShuffleEffect. Can now target any cell, filled or empty (follow-up explicit request: "Toutes les tuiles peuvent être empoisonné, pas juste les tuiles rempli"), and spreads via "contamination" when triggered (see RunManager.ContaminateAdjacentCell, follow-up explicit request: "Si une tuile empoisonnée est triggered, une de ses 4 tuile adjacente est contaminée").</summary>
        public static readonly EnemyDefinition Poisoner = new EnemyDefinition { Id = EnemyId.Poisoner, Name = "Poisoner", Role = EnemyRole.Creator, MaxHp = 1050, Description = "On each Shuffle, poisons 1 tile (filled or empty). Points scored through a poisoned tile count negative instead of positive, and scoring through one spreads it to a random adjacent tile too — all of it clears on the next Shuffle." };

        /// <summary>"Heavy Locker" (GDD §07: Creator/Boss, "High HP. Locks one slot/case until the next Shuffle. Killing it removes the current lock and prevents future locks.") — mechanically Locker's own roaming single-cell lock (see RunManager.ResolveLockerShuffleEffect, reused as-is), just at real boss HP.</summary>
        public static readonly EnemyDefinition HeavyLocker = new EnemyDefinition { Id = EnemyId.HeavyLocker, Name = "Heavy Locker", Role = EnemyRole.Boss, MaxHp = 1800, Description = "On each Shuffle, locks 1 grid cell — same roaming lock as Locker, just far tougher. Killing it releases the lock immediately." };

        /// <summary>"Plague" (GDD §07: Creator/Boss, "High HP. Poisons 5 tiles. Points from those tiles are negative. Killing it normalizes its poisoned tiles.") — Poisoner's own roaming-poison mechanic (see RunManager.ResolvePoisonerShuffleEffect), scaled from 1 cell to 5; same any-tile-targeting and contamination redesign as Poisoner.</summary>
        public static readonly EnemyDefinition Plague = new EnemyDefinition { Id = EnemyId.Plague, Name = "Plague", Role = EnemyRole.Boss, MaxHp = 2700, Description = "On each Shuffle, poisons 5 tiles at once, filled or empty (releasing its previous 5 and any contamination first). Points scored through any of them count negative, and spread to a random adjacent tile." };

        /// <summary>"Thief" (GDD §07: Creator/Boss, "High HP. On each Shuffle, steals 1 random tile from the hand.") — see DeckManager.StealRandomHandTile/RunManager.ResolveThiefShuffleEffect.</summary>
        public static readonly EnemyDefinition Thief = new EnemyDefinition { Id = EnemyId.Thief, Name = "Thief", Role = EnemyRole.Boss, MaxHp = 1500, Description = "On each Shuffle, steals 1 random piece from your hand — it's not lost, just unavailable until a later Shuffle draws it again." };

        /// <summary>"Reclaimer" (redesign, explicit request: "Chaque points négatifs triggered par une tuile empoisonné, l'ennemi reclaimer récupère en point de vie ce montant là") — see RunManager.HealReclaimer/ApplyPoisonScoreRule. Has no On-Shuffle effect of its own at all any more; the GDD's original "consumes poisoned tiles on Shuffle" mechanic (and its order-dependence on Poisoner) no longer applies. Follow-up explicit request ("s'il est heal ET qu'il est full health, il augmente son max health et son health pour devenir plus fort") added the grow-on-overflow-heal mechanic — see EnemyInstance.HealOrGrow.</summary>
        public static readonly EnemyDefinition Reclaimer = new EnemyDefinition { Id = EnemyId.Reclaimer, Name = "Reclaimer", Role = EnemyRole.Boss, MaxHp = 1650, Description = "Heals by the exact amount any poisoned tile's points get flipped negative, anywhere on the board. If it's already at full health, that heal grows its max HP instead — the more you're forced to play into poison once it's topped up, the tougher it gets." };

        /// <summary>"Leech" (GDD §07: Reactor, "High HP. Heals when the player destroys a line. The effect stops when it dies.") — not Boss-tagged, unlike the other 4 new enemies above (per the GDD's own Role column). See RunManager.PlacePiece's own Leech heal hook.</summary>
        public static readonly EnemyDefinition Leech = new EnemyDefinition { Id = EnemyId.Leech, Name = "Leech", Role = EnemyRole.Reactor, MaxHp = 900, Description = "Heals " + ScoringConstants.LeechHealPerLineClear + " HP every time you clear a row or column, for as long as it's alive." };

        private static readonly EnemyDefinition[] All = { Basic, Locker, Poisoner, HeavyLocker, Plague, Thief, Reclaimer, Leech };

        public static EnemyDefinition Get(EnemyId id)
        {
            for (int i = 0; i < All.Length; i++)
            {
                if (All[i].Id == id)
                {
                    return All[i];
                }
            }
            return Basic;
        }
    }
}
